name: 'Deploy Gatsby to AWS S3'
description: 'Deploy a Gatsby Project to an AWS S3 bucket (optional Cloudfront support)'
author: 'jonelantha'
inputs:
  public-source-path:
    description: 'Path to Gatsby /public directory'
    default: './public/'
  dest-s3-bucket:
    description: 'Destination S3 Bucket'
    required: true
  dest-s3-path:
    description: 'Destination S3 Path'
  sync-delete:
    description: "Boolean, delete files on S3 not present in build (default: true)"
    default: 'true'
  browser-cache-duration:
    description: 'Browser cache duration (sec) for cache control headers'
    default: '31536000'
  cdn-cache-duration:
    description: 'CDN cache duration (sec) for cache control headers (sec)'
    default: '31536000'
  cloudfront-id-to-invalidate:
    description: 'Cloudfront ID to invalidate'
  cloudfront-path-to-invalidate:
    description: "Cloudfront Path to invalidate (optional, default: '/*')"
    default: '/*'
  debug:
    description: "Boolean, enable debug logging (default: false)"
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
